name: debug
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  sync:
    name: Sync
    runs-on: ubuntu-latest
    env:
      NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
      NOTION_PAGE: ${{ secrets.NOTION_PAGE }}
      REFRESH_TOKEN: ${{ secrets.REFRESH_TOKEN }}
      CC_URL: ${{ secrets.CC_URL }}
      CC_ID: ${{ secrets.CC_ID }}
      CC_PASSWORD: ${{ secrets.CC_PASSWORD }}
      BOOK_DATABASE_NAME: ${{ vars.BOOK_DATABASE_NAME }}
      AUTHOR_DATABASE_NAME: ${{ vars.AUTHOR_DATABASE_NAME }}
      CATEGORY_DATABASE_NAME: ${{ vars.CATEGORY_DATABASE_NAME }}
      BOOKMARK_DATABASE_NAME: ${{ vars.BOOKMARK_DATABASE_NAME }}
      REVIEW_DATABASE_NAME: ${{ vars.REVIEW_DATABASE_NAME }}
      CHAPTER_DATABASE_NAME: ${{ vars.CHAPTER_DATABASE_NAME }}
      YEAR_DATABASE_NAME: ${{ vars.YEAR_DATABASE_NAME }}
      WEEK_DATABASE_NAME: ${{ vars.WEEK_DATABASE_NAME }}
      MONTH_DATABASE_NAME: ${{ vars.MONTH_DATABASE_NAME }}
      DAY_DATABASE_NAME: ${{ vars.DAY_DATABASE_NAME }}
      REF: ${{ github.ref }}
      REPOSITORY: ${{ github.repository }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Set up secret file
        env:
          USER_NAME: ${{ secrets.USER_NAME }}
          JWT: ${{ secrets.JWT }}
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
          NOTION_PAGE: ${{ secrets.NOTION_PAGE }}
        run: |
          echo $USER_NAME >> secrets.txt
          echo $JWT >> secrets.txt
          echo $NOTION_TOKEN >> secrets.txt
          echo $NOTION_PAGE >> secrets.txt
      - name: push
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m 'add new heatmap' || echo "nothing to commit"
          git push || echo "nothing to push"
    
